// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5dM9UnYsvfEoD9s5R_TFHeOEP7TUHQ3g',
    appId: '1:890500108241:web:1f53a00935fa1f00c41af0',
    messagingSenderId: '890500108241',
    projectId: 'laboratoriska-vezba-4a8c4',
    authDomain: 'laboratoriska-vezba-4a8c4.firebaseapp.com',
    storageBucket: 'laboratoriska-vezba-4a8c4.firebasestorage.app',
    measurementId: 'G-JW01V2S2PZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqIz3-nDVS4jeV1OqIYdjXvJsXAca2iXs',
    appId: '1:890500108241:android:0f3a3e708ccda18cc41af0',
    messagingSenderId: '890500108241',
    projectId: 'laboratoriska-vezba-4a8c4',
    storageBucket: 'laboratoriska-vezba-4a8c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHQr4ni1tMP9dW39jJ2DpsEZF2draODkE',
    appId: '1:890500108241:ios:7d02a3099ba85b99c41af0',
    messagingSenderId: '890500108241',
    projectId: 'laboratoriska-vezba-4a8c4',
    storageBucket: 'laboratoriska-vezba-4a8c4.firebasestorage.app',
    iosBundleId: 'com.example.lab2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHQr4ni1tMP9dW39jJ2DpsEZF2draODkE',
    appId: '1:890500108241:ios:7d02a3099ba85b99c41af0',
    messagingSenderId: '890500108241',
    projectId: 'laboratoriska-vezba-4a8c4',
    storageBucket: 'laboratoriska-vezba-4a8c4.firebasestorage.app',
    iosBundleId: 'com.example.lab2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5dM9UnYsvfEoD9s5R_TFHeOEP7TUHQ3g',
    appId: '1:890500108241:web:3bf03f08c274d08ec41af0',
    messagingSenderId: '890500108241',
    projectId: 'laboratoriska-vezba-4a8c4',
    authDomain: 'laboratoriska-vezba-4a8c4.firebaseapp.com',
    storageBucket: 'laboratoriska-vezba-4a8c4.firebasestorage.app',
    measurementId: 'G-54RG78L6PG',
  );

}